<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Faker\Factory as Faker;
use Carbon\Carbon;


class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // پاکسازی جدول products (اختیاری)
        DB::table('products')->delete();

        DB::table('products')->insert([
            [
                'name'         => 'مادربرد قدرتمند',
                'description'  => 'حجم حافظه: 64GB، فرکانس پردازنده: 3.6GHz، نسل: 12، پورت‌ها: USB-C و HDMI.',
                'brand'        => 'اینتل',
                'price'        => 5000000,
                'quntity'     => 10,
                'category_id'  => 1,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'مادربرد حرفه‌ای',
                'description'  => 'حجم حافظه: 128GB، فرکانس پردازنده: 4.0GHz، نسل: 11، پورت‌ها: USB 3.0 و DisplayPort.',
                'brand'        => 'اسوس',
                'price'        => 4500000,
                'quntity'     => 8,
                'category_id'  => 1,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'مادربرد اقتصادی',
                'description'  => 'حجم حافظه: 32GB، فرکانس پردازنده: 2.8GHz، نسل: 10، پورت‌ها: VGA و USB 2.0.',
                'brand'        => 'مایکروتک',
                'price'        => 3000000,
                'quntity'     => 15,
                'category_id'  => 1,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'مادربرد پیشرفته',
                'description'  => 'حجم حافظه: 256GB، فرکانس پردازنده: 4.2GHz، نسل: 13، پورت‌ها: Thunderbolt 4 و HDMI.',
                'brand'        => 'اینوکس',
                'price'        => 5500000,
                'quntity'     => 7,
                'category_id'  => 1,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'مادربرد اورکلاک',
                'description'  => 'حجم حافظه: 128GB، فرکانس پردازنده: 5.0GHz، نسل: 12، پورت‌ها: USB-C و HDMI.',
                'brand'        => 'جی‌پی‌ایکس',
                'price'        => 6000000,
                'quntity'     => 6,
                'category_id'  => 1,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'مادربرد مدرن',
                'description'  => 'حجم حافظه: 64GB، فرکانس پردازنده: 3.2GHz، نسل: 11، پورت‌ها: USB-C و DisplayPort.',
                'brand'        => 'فاستل',
                'price'        => 5200000,
                'quntity'     => 9,
                'category_id'  => 1,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'مادربرد گیمینگ',
                'description'  => 'حجم حافظه: 256GB، فرکانس پردازنده: 4.5GHz، نسل: 13، پورت‌ها: USB-C و Thunderbolt 4.',
                'brand'        => 'ایم‌ویو',
                'price'        => 5800000,
                'quntity'     => 12,
                'category_id'  => 1,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'مادربرد چند سیستمی',
                'description'  => 'حجم حافظه: 128GB، فرکانس پردازنده: 3.8GHz، نسل: 12، پورت‌ها: USB-C و VGA.',
                'brand'        => 'آرتموس',
                'price'        => 4900000,
                'quntity'     => 11,
                'category_id'  => 1,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'مادربرد سبک و فشرده',
                'description'  => 'حجم حافظه: 32GB، فرکانس پردازنده: 2.5GHz، نسل: 10، پورت‌ها: USB 2.0 و HDMI.',
                'brand'        => 'بایوتک',
                'price'        => 4000000,
                'quntity'     => 20,
                'category_id'  => 1,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'مادربرد ارزان قیمت',
                'description'  => 'حجم حافظه: 16GB، فرکانس پردازنده: 2.2GHz، نسل: 9، پورت‌ها: VGA و USB 2.0.',
                'brand'        => 'نوین',
                'price'        => 2500000,
                'quntity'     => 25,
                'category_id'  => 1,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'پردازنده قدرتمند',
                'description'  => 'فرکانس: 3.6GHz، تعداد هسته: 8، نسل: 12، توان مصرفی: 65W.',
                'brand'        => 'اینتل',
                'price'        => 5500000,
                'quntity'      => 15,
                'category_id'  => 2,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'پردازنده اقتصادی',
                'description'  => 'فرکانس: 2.8GHz، تعداد هسته: 4، نسل: 10، توان مصرفی: 35W.',
                'brand'        => 'AMD',
                'price'        => 3200000,
                'quntity'      => 20,
                'category_id'  => 2,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'پردازنده حرفه‌ای',
                'description'  => 'فرکانس: 4.2GHz، تعداد هسته: 12، نسل: 13، توان مصرفی: 95W.',
                'brand'        => 'اینتل',
                'price'        => 7500000,
                'quntity'      => 10,
                'category_id'  => 2,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'پردازنده میان‌رده',
                'description'  => 'فرکانس: 3.0GHz، تعداد هسته: 6، نسل: 11، توان مصرفی: 45W.',
                'brand'        => 'AMD',
                'price'        => 4500000,
                'quntity'      => 18,
                'category_id'  => 2,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'پردازنده گیمینگ',
                'description'  => 'فرکانس: 5.0GHz، تعداد هسته: 16، نسل: 12، توان مصرفی: 125W.',
                'brand'        => 'اینتل',
                'price'        => 8500000,
                'quntity'      => 12,
                'category_id'  => 2,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'پردازنده سبک',
                'description'  => 'فرکانس: 2.0GHz، تعداد هسته: 2، نسل: 9، توان مصرفی: 25W.',
                'brand'        => 'AMD',
                'price'        => 2000000,
                'quntity'      => 30,
                'category_id'  => 2,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'پردازنده پیشرفته',
                'description'  => 'فرکانس: 4.8GHz، تعداد هسته: 10، نسل: 13، توان مصرفی: 85W.',
                'brand'        => 'اینتل',
                'price'        => 7200000,
                'quntity'      => 8,
                'category_id'  => 2,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'پردازنده چندمنظوره',
                'description'  => 'فرکانس: 3.5GHz، تعداد هسته: 6، نسل: 11، توان مصرفی: 50W.',
                'brand'        => 'AMD',
                'price'        => 4900000,
                'quntity'      => 14,
                'category_id'  => 2,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'پردازنده کم‌مصرف',
                'description'  => 'فرکانس: 2.4GHz، تعداد هسته: 4، نسل: 10، توان مصرفی: 20W.',
                'brand'        => 'اینتل',
                'price'        => 2700000,
                'quntity'      => 25,
                'category_id'  => 2,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'پردازنده نوآورانه',
                'description'  => 'فرکانس: 4.6GHz، تعداد هسته: 14، نسل: 12، توان مصرفی: 105W.',
                'brand'        => 'AMD',
                'price'        => 6700000,
                'quntity'      => 11,
                'category_id'  => 2,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کارت گرافیک قدرتمند',
                'description'  => 'حافظه گرافیکی: 8GB، نوع حافظه: GDDR6، باس: 256-bit، فرکانس پردازنده: 1800MHz.',
                'brand'        => 'اینتل',
                'price'        => 8000000,
                'quntity'      => 10,
                'category_id'  => 3,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کارت گرافیک حرفه‌ای',
                'description'  => 'حافظه گرافیکی: 12GB، نوع حافظه: GDDR6X، باس: 320-bit، فرکانس پردازنده: 1900MHz.',
                'brand'        => 'انویدیا',
                'price'        => 12000000,
                'quntity'      => 8,
                'category_id'  => 3,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کارت گرافیک اقتصادی',
                'description'  => 'حافظه گرافیکی: 4GB، نوع حافظه: GDDR5، باس: 128-bit، فرکانس پردازنده: 1400MHz.',
                'brand'        => 'AMD',
                'price'        => 5000000,
                'quntity'      => 15,
                'category_id'  => 3,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کارت گرافیک میان‌رده',
                'description'  => 'حافظه گرافیکی: 6GB، نوع حافظه: GDDR6، باس: 192-bit، فرکانس پردازنده: 1600MHz.',
                'brand'        => 'انویدیا',
                'price'        => 7000000,
                'quntity'      => 12,
                'category_id'  => 3,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کارت گرافیک گیمینگ',
                'description'  => 'حافظه گرافیکی: 16GB، نوع حافظه: GDDR6X، باس: 384-bit، فرکانس پردازنده: 2100MHz.',
                'brand'        => 'AMD',
                'price'        => 15000000,
                'quntity'      => 6,
                'category_id'  => 3,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کارت گرافیک سبک',
                'description'  => 'حافظه گرافیکی: 2GB، نوع حافظه: GDDR5، باس: 64-bit، فرکانس پردازنده: 1200MHz.',
                'brand'        => 'اینتل',
                'price'        => 3000000,
                'quntity'      => 20,
                'category_id'  => 3,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کارت گرافیک پیشرفته',
                'description'  => 'حافظه گرافیکی: 10GB، نوع حافظه: GDDR6X، باس: 256-bit، فرکانس پردازنده: 2000MHz.',
                'brand'        => 'انویدیا',
                'price'        => 10000000,
                'quntity'      => 9,
                'category_id'  => 3,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کارت گرافیک چندمنظوره',
                'description'  => 'حافظه گرافیکی: 8GB، نوع حافظه: GDDR6، باس: 128-bit، فرکانس پردازنده: 1700MHz.',
                'brand'        => 'AMD',
                'price'        => 8500000,
                'quntity'      => 11,
                'category_id'  => 3,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کارت گرافیک کم‌مصرف',
                'description'  => 'حافظه گرافیکی: 3GB، نوع حافظه: GDDR5، باس: 96-bit، فرکانس پردازنده: 1300MHz.',
                'brand'        => 'اینتل',
                'price'        => 4000000,
                'quntity'      => 18,
                'category_id'  => 3,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کارت گرافیک نوآورانه',
                'description'  => 'حافظه گرافیکی: 12GB، نوع حافظه: GDDR6X، باس: 320-bit، فرکانس پردازنده: 2200MHz.',
                'brand'        => 'انویدیا',
                'price'        => 14000000,
                'quntity'      => 7,
                'category_id'  => 3,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'رم DDR4 قدرتمند',
                'description'  => 'ظرفیت: 16GB، نوع حافظه: DDR4، فرکانس: 3200MHz، زمان تأخیر: CL16.',
                'brand'        => 'کورسیر',
                'price'        => 1500000,
                'quntity'      => 20,
                'category_id'  => 4,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'رم DDR4 حرفه‌ای',
                'description'  => 'ظرفیت: 32GB، نوع حافظه: DDR4، فرکانس: 3600MHz، زمان تأخیر: CL18.',
                'brand'        => 'جی اسکیل',
                'price'        => 2800000,
                'quntity'      => 15,
                'category_id'  => 4,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'رم DDR3 اقتصادی',
                'description'  => 'ظرفیت: 8GB، نوع حافظه: DDR3، فرکانس: 1600MHz، زمان تأخیر: CL10.',
                'brand'        => 'کروشیال',
                'price'        => 800000,
                'quntity'      => 25,
                'category_id'  => 4,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'رم DDR5 پیشرفته',
                'description'  => 'ظرفیت: 64GB، نوع حافظه: DDR5، فرکانس: 5200MHz، زمان تأخیر: CL40.',
                'brand'        => 'کینگستون',
                'price'        => 5500000,
                'quntity'      => 10,
                'category_id'  => 4,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'رم گیمینگ RGB',
                'description'  => 'ظرفیت: 32GB، نوع حافظه: DDR4، فرکانس: 4000MHz، زمان تأخیر: CL18، با نورپردازی RGB.',
                'brand'        => 'کورسیر',
                'price'        => 3000000,
                'quntity'      => 12,
                'category_id'  => 4,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'رم میان‌رده DDR4',
                'description'  => 'ظرفیت: 16GB، نوع حافظه: DDR4، فرکانس: 2400MHz، زمان تأخیر: CL15.',
                'brand'        => 'ادیتا',
                'price'        => 1300000,
                'quntity'      => 18,
                'category_id'  => 4,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'رم حرفه‌ای DDR5',
                'description'  => 'ظرفیت: 32GB، نوع حافظه: DDR5، فرکانس: 6000MHz، زمان تأخیر: CL36.',
                'brand'        => 'جی اسکیل',
                'price'        => 7000000,
                'quntity'      => 8,
                'category_id'  => 4,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'رم کم‌مصرف DDR3',
                'description'  => 'ظرفیت: 4GB، نوع حافظه: DDR3، فرکانس: 1333MHz، زمان تأخیر: CL9.',
                'brand'        => 'کروشیال',
                'price'        => 500000,
                'quntity'      => 30,
                'category_id'  => 4,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'رم سریع DDR4',
                'description'  => 'ظرفیت: 64GB، نوع حافظه: DDR4، فرکانس: 4266MHz، زمان تأخیر: CL19.',
                'brand'        => 'کینگستون',
                'price'        => 4500000,
                'quntity'      => 11,
                'category_id'  => 4,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'رم اقتصادی DDR4',
                'description'  => 'ظرفیت: 8GB، نوع حافظه: DDR4، فرکانس: 2133MHz، زمان تأخیر: CL14.',
                'brand'        => 'ادیتا',
                'price'        => 900000,
                'quntity'      => 22,
                'category_id'  => 4,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'منبع تغذیه قدرتمند',
                'description'  => 'توان خروجی: 850W، نوع اتصال: Full Modular، گواهینامه: 80 Plus Gold.',
                'brand'        => 'کورسیر',
                'price'        => 3000000,
                'quntity'      => 12,
                'category_id'  => 5,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'منبع تغذیه اقتصادی',
                'description'  => 'توان خروجی: 500W، نوع اتصال: Non-Modular، گواهینامه: 80 Plus Bronze.',
                'brand'        => 'اینوکس',
                'price'        => 1200000,
                'quntity'      => 25,
                'category_id'  => 5,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'منبع تغذیه حرفه‌ای',
                'description'  => 'توان خروجی: 1000W، نوع اتصال: Full Modular، گواهینامه: 80 Plus Platinum.',
                'brand'        => 'کورسیر',
                'price'        => 5000000,
                'quntity'      => 10,
                'category_id'  => 5,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'منبع تغذیه میان‌رده',
                'description'  => 'توان خروجی: 750W، نوع اتصال: Semi-Modular، گواهینامه: 80 Plus Silver.',
                'brand'        => 'جی‌اسکیل',
                'price'        => 2500000,
                'quntity'      => 15,
                'category_id'  => 5,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'منبع تغذیه گیمینگ',
                'description'  => 'توان خروجی: 1200W، نوع اتصال: Full Modular، گواهینامه: 80 Plus Titanium.',
                'brand'        => 'اینوکس',
                'price'        => 6000000,
                'quntity'      => 8,
                'category_id'  => 5,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'منبع تغذیه سبک',
                'description'  => 'توان خروجی: 350W، نوع اتصال: Non-Modular، گواهینامه: 80 Plus Standard.',
                'brand'        => 'ادیتا',
                'price'        => 800000,
                'quntity'      => 30,
                'category_id'  => 5,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'منبع تغذیه کم‌مصرف',
                'description'  => 'توان خروجی: 450W، نوع اتصال: Semi-Modular، گواهینامه: 80 Plus Bronze.',
                'brand'        => 'کروشیال',
                'price'        => 1400000,
                'quntity'      => 20,
                'category_id'  => 5,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'منبع تغذیه پیشرفته',
                'description'  => 'توان خروجی: 900W، نوع اتصال: Full Modular، گواهینامه: 80 Plus Gold.',
                'brand'        => 'جی‌اسکیل',
                'price'        => 3500000,
                'quntity'      => 11,
                'category_id'  => 5,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'منبع تغذیه نوآورانه',
                'description'  => 'توان خروجی: 1100W، نوع اتصال: Full Modular، گواهینامه: 80 Plus Platinum.',
                'brand'        => 'کورسیر',
                'price'        => 5200000,
                'quntity'      => 9,
                'category_id'  => 5,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'منبع تغذیه اقتصادی پلاس',
                'description'  => 'توان خروجی: 600W، نوع اتصال: Semi-Modular، گواهینامه: 80 Plus Bronze.',
                'brand'        => 'ادیتا',
                'price'        => 1800000,
                'quntity'      => 22,
                'category_id'  => 5,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'هارد دیسک 1 ترابایت HDD',
                'description'  => 'ظرفیت: 1TB، سرعت چرخش: 7200rpm، نوع اتصال: SATA III.',
                'brand'        => 'وسترن دیجیتال',
                'price'        => 1200000,
                'quntity'      => 30,
                'category_id'  => 6,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'هارد دیسک 2 ترابایت HDD',
                'description'  => 'ظرفیت: 2TB، سرعت چرخش: 7200rpm، نوع اتصال: SATA III.',
                'brand'        => 'سیگیت',
                'price'        => 2000000,
                'quntity'      => 25,
                'category_id'  => 6,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'هارد دیسک 500 گیگابایت HDD',
                'description'  => 'ظرفیت: 500GB، سرعت چرخش: 5400rpm، نوع اتصال: SATA II.',
                'brand'        => 'سامسونگ',
                'price'        => 850000,
                'quntity'      => 40,
                'category_id'  => 6,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'هارد دیسک 4 ترابایت HDD',
                'description'  => 'ظرفیت: 4TB، سرعت چرخش: 7200rpm، نوع اتصال: USB 3.0.',
                'brand'        => 'سیگیت',
                'price'        => 3500000,
                'quntity'      => 12,
                'category_id'  => 6,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'هارد دیسک 6 ترابایت HDD',
                'description'  => 'ظرفیت: 6TB، سرعت چرخش: 7200rpm، نوع اتصال: SATA III.',
                'brand'        => 'وسترن دیجیتال',
                'price'        => 4500000,
                'quntity'      => 9,
                'category_id'  => 6,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'هارد دیسک 8 ترابایت HDD',
                'description'  => 'ظرفیت: 8TB، سرعت چرخش: 5400rpm، نوع اتصال: USB 3.1.',
                'brand'        => 'لسی',
                'price'        => 5500000,
                'quntity'      => 8,
                'category_id'  => 6,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'هارد دیسک 3 ترابایت HDD',
                'description'  => 'ظرفیت: 3TB، سرعت چرخش: 5900rpm، نوع اتصال: SATA II.',
                'brand'        => 'کروشیال',
                'price'        => 2400000,
                'quntity'      => 15,
                'category_id'  => 6,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'هارد دیسک 500 گیگابایت HDD',
                'description'  => 'ظرفیت: 500GB، سرعت چرخش: 7200rpm، نوع اتصال: SATA III.',
                'brand'        => 'سیگیت',
                'price'        => 1100000,
                'quntity'      => 20,
                'category_id'  => 6,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'هارد دیسک 2 ترابایت HDD',
                'description'  => 'ظرفیت: 2TB، سرعت چرخش: 5400rpm، نوع اتصال: USB 3.0.',
                'brand'        => 'وسترن دیجیتال',
                'price'        => 1800000,
                'quntity'      => 22,
                'category_id'  => 6,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'هارد دیسک 10 ترابایت HDD',
                'description'  => 'ظرفیت: 10TB، سرعت چرخش: 7200rpm، نوع اتصال: USB-C.',
                'brand'        => 'سامسونگ',
                'price'        => 7000000,
                'quntity'      => 5,
                'category_id'  => 6,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'هارد دیسک SSD 256GB',
                'description'  => 'ظرفیت: 256GB، سرعت خواندن: 550MB/s، سرعت نوشتن: 500MB/s، نوع اتصال: SATA III.',
                'brand'        => 'سامسونگ',
                'price'        => 1200000,
                'quntity'      => 25,
                'category_id'  => 7,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'هارد دیسک SSD 512GB',
                'description'  => 'ظرفیت: 512GB، سرعت خواندن: 560MB/s، سرعت نوشتن: 530MB/s، نوع اتصال: SATA III.',
                'brand'        => 'وسترن دیجیتال',
                'price'        => 1800000,
                'quntity'      => 20,
                'category_id'  => 7,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'هارد دیسک SSD 1TB',
                'description'  => 'ظرفیت: 1TB، سرعت خواندن: 3500MB/s، سرعت نوشتن: 3000MB/s، نوع اتصال: NVMe.',
                'brand'        => 'کروشیال',
                'price'        => 3500000,
                'quntity'      => 15,
                'category_id'  => 7,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'هارد دیسک SSD 2TB',
                'description'  => 'ظرفیت: 2TB، سرعت خواندن: 3400MB/s، سرعت نوشتن: 3000MB/s، نوع اتصال: PCIe.',
                'brand'        => 'سیگیت',
                'price'        => 6000000,
                'quntity'      => 10,
                'category_id'  => 7,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'هارد دیسک SSD 128GB',
                'description'  => 'ظرفیت: 128GB، سرعت خواندن: 520MB/s، سرعت نوشتن: 450MB/s، نوع اتصال: SATA III.',
                'brand'        => 'ادیتا',
                'price'        => 950000,
                'quntity'      => 30,
                'category_id'  => 7,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'هارد دیسک SSD 500GB',
                'description'  => 'ظرفیت: 500GB، سرعت خواندن: 560MB/s، سرعت نوشتن: 530MB/s، نوع اتصال: SATA III.',
                'brand'        => 'وسترن دیجیتال',
                'price'        => 1700000,
                'quntity'      => 22,
                'category_id'  => 7,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'هارد دیسک SSD 1TB NVMe',
                'description'  => 'ظرفیت: 1TB، سرعت خواندن: 5000MB/s، سرعت نوشتن: 4400MB/s، نوع اتصال: NVMe.',
                'brand'        => 'سامسونگ',
                'price'        => 4000000,
                'quntity'      => 12,
                'category_id'  => 7,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'هارد دیسک SSD 4TB',
                'description'  => 'ظرفیت: 4TB، سرعت خواندن: 3500MB/s، سرعت نوشتن: 3000MB/s، نوع اتصال: NVMe.',
                'brand'        => 'کروشیال',
                'price'        => 8000000,
                'quntity'      => 8,
                'category_id'  => 7,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'هارد دیسک SSD 2TB PCIe',
                'description'  => 'ظرفیت: 2TB، سرعت خواندن: 3200MB/s، سرعت نوشتن: 2900MB/s، نوع اتصال: PCIe.',
                'brand'        => 'سیگیت',
                'price'        => 5800000,
                'quntity'      => 9,
                'category_id'  => 7,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'هارد دیسک SSD 250GB',
                'description'  => 'ظرفیت: 250GB، سرعت خواندن: 500MB/s، سرعت نوشتن: 450MB/s، نوع اتصال: SATA III.',
                'brand'        => 'ادیتا',
                'price'        => 1200000,
                'quntity'      => 28,
                'category_id'  => 7,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'فن RGB 120mm',
                'description'  => 'اندازه: 120mm، سرعت چرخش: 1500rpm، نویز: 25dB، نوع اتصال: 4-Pin PWM.',
                'brand'        => 'کورسیر',
                'price'        => 300000,
                'quntity'      => 30,
                'category_id'  => 8,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'فن گیمینگ 140mm',
                'description'  => 'اندازه: 140mm، سرعت چرخش: 1700rpm، نویز: 30dB، نوع اتصال: 4-Pin PWM.',
                'brand'        => 'جی‌اسکیل',
                'price'        => 450000,
                'quntity'      => 25,
                'category_id'  => 8,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'فن اقتصادی 92mm',
                'description'  => 'اندازه: 92mm، سرعت چرخش: 1200rpm، نویز: 20dB، نوع اتصال: 3-Pin.',
                'brand'        => 'ادیتا',
                'price'        => 200000,
                'quntity'      => 40,
                'category_id'  => 8,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'فن پیشرفته 120mm',
                'description'  => 'اندازه: 120mm، سرعت چرخش: 2000rpm، نویز: 28dB، نوع اتصال: 4-Pin PWM.',
                'brand'        => 'سیگیت',
                'price'        => 500000,
                'quntity'      => 15,
                'category_id'  => 8,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'فن بی‌صدا 140mm',
                'description'  => 'اندازه: 140mm، سرعت چرخش: 1000rpm، نویز: 15dB، نوع اتصال: 3-Pin.',
                'brand'        => 'کروشیال',
                'price'        => 350000,
                'quntity'      => 20,
                'category_id'  => 8,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'فن خنک‌کننده RGB 120mm',
                'description'  => 'اندازه: 120mm، سرعت چرخش: 1600rpm، نویز: 27dB، نوع اتصال: 4-Pin PWM.',
                'brand'        => 'سامسونگ',
                'price'        => 400000,
                'quntity'      => 18,
                'category_id'  => 8,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'فن حرفه‌ای 200mm',
                'description'  => 'اندازه: 200mm، سرعت چرخش: 800rpm، نویز: 24dB، نوع اتصال: 4-Pin PWM.',
                'brand'        => 'کورسیر',
                'price'        => 600000,
                'quntity'      => 10,
                'category_id'  => 8,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'فن کم‌مصرف 92mm',
                'description'  => 'اندازه: 92mm، سرعت چرخش: 1000rpm، نویز: 18dB، نوع اتصال: 3-Pin.',
                'brand'        => 'ادیتا',
                'price'        => 180000,
                'quntity'      => 35,
                'category_id'  => 8,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'فن سریع 120mm',
                'description'  => 'اندازه: 120mm، سرعت چرخش: 2200rpm، نویز: 30dB، نوع اتصال: 4-Pin PWM.',
                'brand'        => 'سیگیت',
                'price'        => 500000,
                'quntity'      => 12,
                'category_id'  => 8,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'فن RGB 140mm',
                'description'  => 'اندازه: 140mm، سرعت چرخش: 1500rpm، نویز: 25dB، نوع اتصال: 4-Pin PWM.',
                'brand'        => 'سامسونگ',
                'price'        => 450000,
                'quntity'      => 22,
                'category_id'  => 8,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'مانیتور 24 اینچ Full HD',
                'description'  => 'اندازه: 24 اینچ، نوع پنل: IPS، رزولوشن: 1920x1080، نرخ تازه‌سازی: 75Hz.',
                'brand'        => 'LG',
                'price'        => 3500000,
                'quntity'      => 20,
                'category_id'  => 9,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'مانیتور 27 اینچ QHD',
                'description'  => 'اندازه: 27 اینچ، نوع پنل: VA، رزولوشن: 2560x1440، نرخ تازه‌سازی: 144Hz.',
                'brand'        => 'سامسونگ',
                'price'        => 5500000,
                'quntity'      => 15,
                'category_id'  => 9,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'مانیتور 32 اینچ 4K UHD',
                'description'  => 'اندازه: 32 اینچ، نوع پنل: IPS، رزولوشن: 3840x2160، نرخ تازه‌سازی: 60Hz.',
                'brand'        => 'ایسر',
                'price'        => 7500000,
                'quntity'      => 10,
                'category_id'  => 9,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'مانیتور گیمینگ 27 اینچ Full HD',
                'description'  => 'اندازه: 27 اینچ، نوع پنل: TN، رزولوشن: 1920x1080، نرخ تازه‌سازی: 240Hz.',
                'brand'        => 'ایسوس',
                'price'        => 6000000,
                'quntity'      => 12,
                'category_id'  => 9,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'مانیتور 34 اینچ UltraWide',
                'description'  => 'اندازه: 34 اینچ، نوع پنل: VA، رزولوشن: 3440x1440، نرخ تازه‌سازی: 100Hz.',
                'brand'        => 'سامسونگ',
                'price'        => 8500000,
                'quntity'      => 8,
                'category_id'  => 9,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'مانیتور 22 اینچ HD',
                'description'  => 'اندازه: 22 اینچ، نوع پنل: IPS، رزولوشن: 1366x768، نرخ تازه‌سازی: 60Hz.',
                'brand'        => 'ایسر',
                'price'        => 2500000,
                'quntity'      => 25,
                'category_id'  => 9,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'مانیتور گیمینگ 32 اینچ QHD',
                'description'  => 'اندازه: 32 اینچ، نوع پنل: IPS، رزولوشن: 2560x1440، نرخ تازه‌سازی: 165Hz.',
                'brand'        => 'ایسوس',
                'price'        => 9000000,
                'quntity'      => 7,
                'category_id'  => 9,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'مانیتور 27 اینچ Curved Full HD',
                'description'  => 'اندازه: 27 اینچ، نوع پنل: VA، رزولوشن: 1920x1080، نرخ تازه‌سازی: 75Hz.',
                'brand'        => 'سامسونگ',
                'price'        => 4800000,
                'quntity'      => 14,
                'category_id'  => 9,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'مانیتور 29 اینچ UltraWide Full HD',
                'description'  => 'اندازه: 29 اینچ، نوع پنل: IPS، رزولوشن: 2560x1080، نرخ تازه‌سازی: 75Hz.',
                'brand'        => 'LG',
                'price'        => 6200000,
                'quntity'      => 11,
                'category_id'  => 9,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'مانیتور 24 اینچ Full HD',
                'description'  => 'اندازه: 24 اینچ، نوع پنل: TN، رزولوشن: 1920x1080، نرخ تازه‌سازی: 60Hz.',
                'brand'        => 'ایسر',
                'price'        => 3400000,
                'quntity'      => 18,
                'category_id'  => 9,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کیبورد مکانیکال RGB',
                'description'  => 'نوع: مکانیکال، نورپردازی: RGB، تعداد کلیدها: 104، اتصال: USB.',
                'brand'        => 'کورسیر',
                'price'        => 2000000,
                'quntity'      => 15,
                'category_id'  => 10,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کیبورد گیمینگ مکانیکال',
                'description'  => 'نوع: مکانیکال، نورپردازی: تک‌رنگ قرمز، تعداد کلیدها: 87 (Tenkeyless)، اتصال: USB.',
                'brand'        => 'لاجیتک',
                'price'        => 1800000,
                'quntity'      => 20,
                'category_id'  => 10,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کیبورد بی‌سیم',
                'description'  => 'نوع: ممبران، اتصال: بی‌سیم (بلوتوث)، تعداد کلیدها: 104، باتری: قابل شارژ.',
                'brand'        => 'مایکروسافت',
                'price'        => 1200000,
                'quntity'      => 25,
                'category_id'  => 10,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کیبورد ارگونومیک',
                'description'  => 'نوع: ممبران، نورپردازی: بدون نور، طراحی: ارگونومیک، تعداد کلیدها: 105.',
                'brand'        => 'مایکروسافت',
                'price'        => 1500000,
                'quntity'      => 18,
                'category_id'  => 10,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کیبورد گیمینگ RGB',
                'description'  => 'نوع: مکانیکال، نورپردازی: RGB، تعداد کلیدها: 108، اتصال: USB-C.',
                'brand'        => 'رِیزر',
                'price'        => 2500000,
                'quntity'      => 12,
                'category_id'  => 10,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کیبورد قابل حمل',
                'description'  => 'نوع: بی‌سیم، نورپردازی: بدون نور، تعداد کلیدها: 61، اتصال: بلوتوث.',
                'brand'        => 'لاجیتک',
                'price'        => 1000000,
                'quntity'      => 30,
                'category_id'  => 10,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کیبورد مالتی‌مدیا',
                'description'  => 'نوع: ممبران، نورپردازی: تک‌رنگ آبی، تعداد کلیدها: 118 (شامل کلیدهای مالتی‌مدیا).',
                'brand'        => 'ایسر',
                'price'        => 1400000,
                'quntity'      => 22,
                'category_id'  => 10,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کیبورد حرفه‌ای گیمینگ',
                'description'  => 'نوع: مکانیکال، نورپردازی: RGB، تعداد کلیدها: 104، اتصال: USB-C.',
                'brand'        => 'رِیزر',
                'price'        => 2800000,
                'quntity'      => 10,
                'category_id'  => 10,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کیبورد اقتصادی',
                'description'  => 'نوع: ممبران، نورپردازی: بدون نور، تعداد کلیدها: 104، اتصال: USB.',
                'brand'        => 'ایسوس',
                'price'        => 700000,
                'quntity'      => 35,
                'category_id'  => 10,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کیبورد گیمینگ ساده',
                'description'  => 'نوع: ممبران، نورپردازی: تک‌رنگ سفید، تعداد کلیدها: 104، اتصال: USB.',
                'brand'        => 'ایسر',
                'price'        => 1100000,
                'quntity'      => 28,
                'category_id'  => 10,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'ماوس گیمینگ RGB',
                'description'  => 'نوع: گیمینگ، DPI: 16000، تعداد کلیدها: 8، اتصال: USB، نورپردازی: RGB.',
                'brand'        => 'لاجیتک',
                'price'        => 2500000,
                'quntity'      => 15,
                'category_id'  => 11,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'ماوس بی‌سیم بلوتوث',
                'description'  => 'نوع: بی‌سیم، DPI: 800، تعداد کلیدها: 3، اتصال: بلوتوث، باتری: قابل شارژ.',
                'brand'        => 'مایکروسافت',
                'price'        => 1200000,
                'quntity'      => 20,
                'category_id'  => 11,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'ماوس ارگونومیک',
                'description'  => 'نوع: ارگونومیک، DPI: 1200، تعداد کلیدها: 6، اتصال: USB، طراحی: ارگونومیک.',
                'brand'        => 'ایسوس',
                'price'        => 1800000,
                'quntity'      => 25,
                'category_id'  => 11,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'ماوس اقتصادی',
                'description'  => 'نوع: استاندارد، DPI: 1000، تعداد کلیدها: 3، اتصال: USB، بدون نورپردازی.',
                'brand'        => 'ادیتا',
                'price'        => 700000,
                'quntity'      => 30,
                'category_id'  => 11,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'ماوس گیمینگ حرفه‌ای',
                'description'  => 'نوع: گیمینگ، DPI: 20000، تعداد کلیدها: 10، اتصال: USB-C، نورپردازی: RGB.',
                'brand'        => 'رِیزر',
                'price'        => 3500000,
                'quntity'      => 12,
                'category_id'  => 11,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'ماوس بی‌سیم ساده',
                'description'  => 'نوع: بی‌سیم، DPI: 1000، تعداد کلیدها: 3، اتصال: RF، باتری: قابل شارژ.',
                'brand'        => 'لاجیتک',
                'price'        => 1000000,
                'quntity'      => 35,
                'category_id'  => 11,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'ماوس مالتی‌مدیا',
                'description'  => 'نوع: استاندارد، DPI: 1200، تعداد کلیدها: 5، اتصال: USB، طراحی: مالتی‌مدیا.',
                'brand'        => 'ایسر',
                'price'        => 1400000,
                'quntity'      => 18,
                'category_id'  => 11,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'ماوس گیمینگ RGB پیشرفته',
                'description'  => 'نوع: گیمینگ، DPI: 18000، تعداد کلیدها: 9، اتصال: USB-C، نورپردازی: RGB.',
                'brand'        => 'رِیزر',
                'price'        => 3200000,
                'quntity'      => 10,
                'category_id'  => 11,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'ماوس کوچک',
                'description'  => 'نوع: قابل حمل، DPI: 1000، تعداد کلیدها: 2، اتصال: USB، بدون نورپردازی.',
                'brand'        => 'ایسوس',
                'price'        => 600000,
                'quntity'      => 40,
                'category_id'  => 11,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'ماوس حرفه‌ای',
                'description'  => 'نوع: استاندارد، DPI: 16000، تعداد کلیدها: 6، اتصال: USB، بدون نورپردازی.',
                'brand'        => 'ایسر',
                'price'        => 2000000,
                'quntity'      => 22,
                'category_id'  => 11,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'درایو نوری DVD',
                'description'  => 'نوع: DVD، سرعت خواندن: 16x، سرعت نوشتن: 8x، نوع اتصال: SATA.',
                'brand'        => 'ایسوس',
                'price'        => 600000,
                'quntity'      => 25,
                'category_id'  => 12,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'درایو نوری Blu-Ray',
                'description'  => 'نوع: Blu-Ray، سرعت خواندن: 6x، سرعت نوشتن: 4x، نوع اتصال: SATA.',
                'brand'        => 'سامسونگ',
                'price'        => 1200000,
                'quntity'      => 20,
                'category_id'  => 12,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'درایو نوری Combo',
                'description'  => 'نوع: DVD + CD، سرعت خواندن: 24x، سرعت نوشتن: 10x، نوع اتصال: USB.',
                'brand'        => 'LG',
                'price'        => 850000,
                'quntity'      => 30,
                'category_id'  => 12,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'درایو نوری Portable',
                'description'  => 'نوع: قابل حمل، سرعت خواندن: 8x، سرعت نوشتن: 4x، نوع اتصال: USB.',
                'brand'        => 'ایسر',
                'price'        => 950000,
                'quntity'      => 18,
                'category_id'  => 12,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'درایو نوری Blu-Ray پیشرفته',
                'description'  => 'نوع: Blu-Ray، سرعت خواندن: 10x، سرعت نوشتن: 6x، نوع اتصال: SATA III.',
                'brand'        => 'وسترن دیجیتال',
                'price'        => 1500000,
                'quntity'      => 12,
                'category_id'  => 12,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'درایو نوری DVD سریع',
                'description'  => 'نوع: DVD، سرعت خواندن: 20x، سرعت نوشتن: 12x، نوع اتصال: SATA.',
                'brand'        => 'سیگیت',
                'price'        => 700000,
                'quntity'      => 28,
                'category_id'  => 12,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'درایو نوری Combo',
                'description'  => 'نوع: Blu-Ray + DVD، سرعت خواندن: 10x، سرعت نوشتن: 6x، نوع اتصال: USB.',
                'brand'        => 'کروشیال',
                'price'        => 1700000,
                'quntity'      => 14,
                'category_id'  => 12,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'درایو نوری ارگونومیک',
                'description'  => 'نوع: DVD، سرعت خواندن: 16x، سرعت نوشتن: 8x، نوع اتصال: USB.',
                'brand'        => 'ایسوس',
                'price'        => 800000,
                'quntity'      => 32,
                'category_id'  => 12,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'درایو نوری Blu-Ray سبک',
                'description'  => 'نوع: Blu-Ray، سرعت خواندن: 8x، سرعت نوشتن: 4x، نوع اتصال: USB.',
                'brand'        => 'سامسونگ',
                'price'        => 1400000,
                'quntity'      => 16,
                'category_id'  => 12,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'درایو نوری DVD اقتصادی',
                'description'  => 'نوع: DVD، سرعت خواندن: 12x، سرعت نوشتن: 6x، نوع اتصال: SATA II.',
                'brand'        => 'LG',
                'price'        => 650000,
                'quntity'      => 35,
                'category_id'  => 12,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کارت صدا حرفه‌ای 5.1 کانال',
                'description'  => 'نوع: 5.1 کانال، نرخ نمونه‌برداری: 192kHz، اتصال: PCIe، پشتیبانی از صدای Dolby.',
                'brand'        => 'Creative',
                'price'        => 1800000,
                'quntity'      => 12,
                'category_id'  => 13,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کارت صدا اقتصادی 2.1 کانال',
                'description'  => 'نوع: 2.1 کانال، نرخ نمونه‌برداری: 96kHz، اتصال: USB، مناسب برای کاربران خانگی.',
                'brand'        => 'ASUS',
                'price'        => 700000,
                'quntity'      => 25,
                'category_id'  => 13,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کارت صدا گیمینگ 7.1 کانال',
                'description'  => 'نوع: 7.1 کانال، نرخ نمونه‌برداری: 384kHz، اتصال: PCIe، پشتیبانی از صدای سه‌بعدی.',
                'brand'        => 'Logitech',
                'price'        => 2500000,
                'quntity'      => 15,
                'category_id'  => 13,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کارت صدا قابل حمل USB',
                'description'  => 'نوع: استریو، نرخ نمونه‌برداری: 48kHz، اتصال: USB، طراحی کوچک و سبک.',
                'brand'        => 'Focusrite',
                'price'        => 600000,
                'quntity'      => 30,
                'category_id'  => 13,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کارت صدا استودیویی 24 بیتی',
                'description'  => 'نوع: استریو، نرخ نمونه‌برداری: 96kHz، اتصال: USB-C، مناسب برای ضبط حرفه‌ای.',
                'brand'        => 'Behringer',
                'price'        => 2800000,
                'quntity'      => 10,
                'category_id'  => 13,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کارت صدا چندمنظوره',
                'description'  => 'نوع: 5.1 کانال، نرخ نمونه‌برداری: 192kHz، اتصال: PCI، مناسب برای فیلم و موسیقی.',
                'brand'        => 'Creative',
                'price'        => 1500000,
                'quntity'      => 18,
                'category_id'  => 13,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کارت صدا بی‌سیم',
                'description'  => 'نوع: استریو، نرخ نمونه‌برداری: 48kHz، اتصال: Bluetooth، سازگار با سیستم‌های مختلف.',
                'brand'        => 'Sony',
                'price'        => 1300000,
                'quntity'      => 20,
                'category_id'  => 13,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کارت صدا گیمینگ پیشرفته',
                'description'  => 'نوع: 7.1 کانال، نرخ نمونه‌برداری: 384kHz، اتصال: USB-C، پشتیبانی از صدای Hi-Res.',
                'brand'        => 'ASUS',
                'price'        => 3000000,
                'quntity'      => 8,
                'category_id'  => 13,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کارت صدا USB اقتصادی',
                'description'  => 'نوع: استریو، نرخ نمونه‌برداری: 44.1kHz، اتصال: USB، مناسب برای تماس‌های ویدیویی.',
                'brand'        => 'Logitech',
                'price'        => 500000,
                'quntity'      => 35,
                'category_id'  => 13,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کارت صدا استودیویی حرفه‌ای',
                'description'  => 'نوع: استریو، نرخ نمونه‌برداری: 192kHz، اتصال: Thunderbolt، مناسب برای تولید موسیقی.',
                'brand'        => 'Focusrite',
                'price'        => 3500000,
                'quntity'      => 7,
                'category_id'  => 13,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کارت شبکه گیگابیتی PCIe',
                'description'  => 'نوع: Gigabit Ethernet، سرعت: 1Gbps، نوع اتصال: PCIe، مناسب برای سرورها.',
                'brand'        => 'اینتل',
                'price'        => 950000,
                'quntity'      => 20,
                'category_id'  => 14,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کارت شبکه بی‌سیم Dual-Band',
                'description'  => 'نوع: Wi-Fi 6، سرعت: 1200Mbps، نوع اتصال: PCIe، پشتیبانی از 2.4 و 5GHz.',
                'brand'        => 'TP-Link',
                'price'        => 1500000,
                'quntity'      => 18,
                'category_id'  => 14,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کارت شبکه USB 3.0',
                'description'  => 'نوع: Gigabit Ethernet، سرعت: 1Gbps، نوع اتصال: USB 3.0، طراحی قابل حمل.',
                'brand'        => 'دی‌لینک',
                'price'        => 750000,
                'quntity'      => 25,
                'category_id'  => 14,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کارت شبکه Wi-Fi 6E',
                'description'  => 'نوع: Wi-Fi 6E، سرعت: 2400Mbps، نوع اتصال: PCIe، پشتیبانی از باند 6GHz.',
                'brand'        => 'ایسوس',
                'price'        => 2200000,
                'quntity'      => 12,
                'category_id'  => 14,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کارت شبکه 10 گیگابیتی',
                'description'  => 'نوع: 10 Gigabit Ethernet، سرعت: 10Gbps، نوع اتصال: PCIe، مناسب برای شبکه‌های پرسرعت.',
                'brand'        => 'اینتل',
                'price'        => 4500000,
                'quntity'      => 8,
                'category_id'  => 14,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کارت شبکه USB بی‌سیم',
                'description'  => 'نوع: Wi-Fi 5، سرعت: 600Mbps، نوع اتصال: USB 2.0، پشتیبانی از 2.4 و 5GHz.',
                'brand'        => 'تی‌پی-لینک',
                'price'        => 500000,
                'quntity'      => 30,
                'category_id'  => 14,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کارت شبکه با آنتن خارجی',
                'description'  => 'نوع: Wi-Fi 6، سرعت: 1800Mbps، نوع اتصال: PCIe، همراه با آنتن خارجی قابل تنظیم.',
                'brand'        => 'دی‌لینک',
                'price'        => 1600000,
                'quntity'      => 15,
                'category_id'  => 14,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کارت شبکه گیمینگ',
                'description'  => 'نوع: Ethernet + Wi-Fi، سرعت: 1Gbps، نوع اتصال: PCIe، بهینه شده برای بازی.',
                'brand'        => 'ایسوس',
                'price'        => 2500000,
                'quntity'      => 10,
                'category_id'  => 14,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کارت شبکه Multi-Gig',
                'description'  => 'نوع: Multi-Gig Ethernet، سرعت: 2.5Gbps، نوع اتصال: PCIe، مناسب برای شبکه‌های مدرن.',
                'brand'        => 'اینتل',
                'price'        => 3200000,
                'quntity'      => 9,
                'category_id'  => 14,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کارت شبکه Dual-Band ارزان',
                'description'  => 'نوع: Wi-Fi 5، سرعت: 867Mbps، نوع اتصال: USB، مناسب برای مصارف خانگی.',
                'brand'        => 'تی‌پی-لینک',
                'price'        => 600000,
                'quntity'      => 28,
                'category_id'  => 14,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کیس گیمینگ RGB ATX',
                'description'  => 'نوع: ATX، جنس بدنه: استیل و شیشه حرارت‌دیده، نورپردازی: RGB، فن‌های پیش‌نصب: 3 عدد.',
                'brand'        => 'کورسیر',
                'price'        => 3500000,
                'quntity'      => 15,
                'category_id'  => 15,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کیس اقتصادی Micro-ATX',
                'description'  => 'نوع: Micro-ATX، جنس بدنه: استیل، بدون نورپردازی، طراحی ساده و مینیمال.',
                'brand'        => 'دیپ کول',
                'price'        => 1000000,
                'quntity'      => 25,
                'category_id'  => 15,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کیس حرفه‌ای Mid Tower',
                'description'  => 'نوع: Mid Tower، جنس بدنه: آلومینیوم، نورپردازی: RGB، فن‌های پیش‌نصب: 2 عدد.',
                'brand'        => 'ایسوس',
                'price'        => 4500000,
                'quntity'      => 10,
                'category_id'  => 15,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کیس گیمینگ Full Tower',
                'description'  => 'نوع: Full Tower، جنس بدنه: استیل و شیشه، نورپردازی: RGB قابل تنظیم، دارای کنترلر نور.',
                'brand'        => 'NZXT',
                'price'        => 5500000,
                'quntity'      => 8,
                'category_id'  => 15,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کیس بی‌صدا Mid Tower',
                'description'  => 'نوع: Mid Tower، جنس بدنه: استیل، بدون نورپردازی، عایق صدا برای کارکرد آرام.',
                'brand'        => 'فرکتال دیزاین',
                'price'        => 3000000,
                'quntity'      => 20,
                'category_id'  => 15,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کیس شیشه‌ای ATX',
                'description'  => 'نوع: ATX، جنس بدنه: شیشه حرارت‌دیده و استیل، نورپردازی: بدون RGB، فضای زیاد برای قطعات.',
                'brand'        => 'دیپ کول',
                'price'        => 2700000,
                'quntity'      => 18,
                'category_id'  => 15,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کیس گیمینگ RGB Mini-ITX',
                'description'  => 'نوع: Mini-ITX، جنس بدنه: استیل و پلاستیک، نورپردازی: RGB، فن‌های پیش‌نصب: 1 عدد.',
                'brand'        => 'NZXT',
                'price'        => 2500000,
                'quntity'      => 12,
                'category_id'  => 15,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کیس اقتصادی Mid Tower',
                'description'  => 'نوع: Mid Tower، جنس بدنه: استیل، بدون نورپردازی، قیمت مقرون‌به‌صرفه.',
                'brand'        => 'کولر مستر',
                'price'        => 2200000,
                'quntity'      => 30,
                'category_id'  => 15,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کیس حرفه‌ای Full Tower',
                'description'  => 'نوع: Full Tower، جنس بدنه: آلومینیوم، نورپردازی: RGB، کنترلر تنظیم سرعت فن.',
                'brand'        => 'ایسوس',
                'price'        => 6000000,
                'quntity'      => 10,
                'category_id'  => 15,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'کیس گیمینگ ساده ATX',
                'description'  => 'نوع: ATX، جنس بدنه: استیل، نورپردازی: بدون RGB، مناسب برای کاربران گیمینگ.',
                'brand'        => 'کورسیر',
                'price'        => 3200000,
                'quntity'      => 15,
                'category_id'  => 15,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'اسپیکر بلوتوث قابل حمل',
                'description'  => 'نوع: بلوتوث، توان خروجی: 10 وات، باتری: 12 ساعت، اتصال: بی‌سیم.',
                'brand'        => 'JBL',
                'price'        => 1200000,
                'quntity'      => 20,
                'category_id'  => 16,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'اسپیکر خانگی 2.1 کانال',
                'description'  => 'نوع: سیمی، توان خروجی: 50 وات، تعداد کانال: 2.1، اتصال: AUX و RCA.',
                'brand'        => 'Logitech',
                'price'        => 1800000,
                'quntity'      => 15,
                'category_id'  => 16,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'اسپیکر گیمینگ RGB',
                'description'  => 'نوع: سیمی، توان خروجی: 40 وات، نورپردازی: RGB، اتصال: USB و AUX.',
                'brand'        => 'Razer',
                'price'        => 2500000,
                'quntity'      => 12,
                'category_id'  => 16,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'اسپیکر بلوتوث پیشرفته',
                'description'  => 'نوع: بلوتوث، توان خروجی: 30 وات، باتری: 24 ساعت، اتصال: بی‌سیم و USB-C.',
                'brand'        => 'Sony',
                'price'        => 3200000,
                'quntity'      => 10,
                'category_id'  => 16,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'اسپیکر دسکتاپ 5 وات',
                'description'  => 'نوع: سیمی، توان خروجی: 5 وات، اتصال: USB و جک 3.5 میلی‌متری.',
                'brand'        => 'Edifier',
                'price'        => 800000,
                'quntity'      => 25,
                'category_id'  => 16,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'اسپیکر 5.1 کانال خانگی',
                'description'  => 'نوع: سیمی، توان خروجی: 100 وات، تعداد کانال: 5.1، اتصال: HDMI و اپتیکال.',
                'brand'        => 'LG',
                'price'        => 4500000,
                'quntity'      => 8,
                'category_id'  => 16,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'اسپیکر پرتابل اقتصادی',
                'description'  => 'نوع: بلوتوث، توان خروجی: 15 وات، باتری: 10 ساعت، اتصال: بی‌سیم و AUX.',
                'brand'        => 'Anker',
                'price'        => 1000000,
                'quntity'      => 18,
                'category_id'  => 16,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'اسپیکر حرفه‌ای گیمینگ',
                'description'  => 'نوع: سیمی، توان خروجی: 60 وات، نورپردازی: RGB، اتصال: USB و Bluetooth.',
                'brand'        => 'Logitech',
                'price'        => 3000000,
                'quntity'      => 10,
                'category_id'  => 16,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'اسپیکر استریو قابل حمل',
                'description'  => 'نوع: بلوتوث، توان خروجی: 20 وات، باتری: 16 ساعت، اتصال: بی‌سیم.',
                'brand'        => 'JBL',
                'price'        => 2200000,
                'quntity'      => 15,
                'category_id'  => 16,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'اسپیکر هوشمند',
                'description'  => 'نوع: بلوتوث، توان خروجی: 25 وات، پشتیبانی از دستیار صوتی، اتصال: Wi-Fi و Bluetooth.',
                'brand'        => 'Amazon',
                'price'        => 2800000,
                'quntity'      => 12,
                'category_id'  => 16,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'هدست گیمینگ RGB',
                'description'  => 'نوع اتصال: USB، میکروفون: بوم جداشدنی، نورپردازی: RGB، صدای سه‌بعدی.',
                'brand'        => 'Razer',
                'price'        => 3500000,
                'quntity'      => 12,
                'category_id'  => 17,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'هدست بلوتوث بی‌سیم',
                'description'  => 'نوع اتصال: بلوتوث، حذف نویز: فعال (ANC)، باتری: 20 ساعت، کیفیت صدا: Hi-Res.',
                'brand'        => 'Sony',
                'price'        => 5000000,
                'quntity'      => 10,
                'category_id'  => 17,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'هدست استریو سیمی',
                'description'  => 'نوع اتصال: جک 3.5 میلی‌متری، میکروفون: داخلی، صدای استریو، طراحی ارگونومیک.',
                'brand'        => 'Logitech',
                'price'        => 1500000,
                'quntity'      => 20,
                'category_id'  => 17,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'هدست استودیویی حرفه‌ای',
                'description'  => 'نوع اتصال: سیمی (جک 6.3 میلی‌متری)، حذف نویز: غیرفعال، مناسب برای ویرایش صدا.',
                'brand'        => 'Audio-Technica',
                'price'        => 7000000,
                'quntity'      => 8,
                'category_id'  => 17,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'هدست اقتصادی بی‌سیم',
                'description'  => 'نوع اتصال: بلوتوث، باتری: 15 ساعت، وزن: سبک، کیفیت صدای شفاف.',
                'brand'        => 'Anker',
                'price'        => 2000000,
                'quntity'      => 25,
                'category_id'  => 17,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'هدست گیمینگ ساده',
                'description'  => 'نوع اتصال: USB، میکروفون: داخلی، صدای استریو، بدون نورپردازی.',
                'brand'        => 'HyperX',
                'price'        => 2500000,
                'quntity'      => 15,
                'category_id'  => 17,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'هدست Hi-Fi بلوتوث',
                'description'  => 'نوع اتصال: بلوتوث 5.0، پشتیبانی از کدک aptX، باتری: 30 ساعت، کیفیت صدا: Hi-Fi.',
                'brand'        => 'Sennheiser',
                'price'        => 6000000,
                'quntity'      => 10,
                'category_id'  => 17,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'هدست نویزگیر اداری',
                'description'  => 'نوع اتصال: USB، حذف نویز: غیرفعال، مناسب برای تماس‌های ویدیویی، وزن: سبک.',
                'brand'        => 'Jabra',
                'price'        => 3000000,
                'quntity'      => 18,
                'category_id'  => 17,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'هدست حرفه‌ای بازی',
                'description'  => 'نوع اتصال: USB-C، صدای فراگیر، میکروفون: قابل تنظیم، نورپردازی: RGB.',
                'brand'        => 'Corsair',
                'price'        => 4500000,
                'quntity'      => 12,
                'category_id'  => 17,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'هدست ورزشی بی‌سیم',
                'description'  => 'نوع اتصال: بلوتوث، ضدآب: IPX5، باتری: 10 ساعت، وزن: فوق‌سبک.',
                'brand'        => 'Bose',
                'price'        => 4000000,
                'quntity'      => 14,
                'category_id'  => 17,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'دوربین وب Full HD',
                'description'  => 'کیفیت تصویر: 1080p، فریم‌ریت: 30fps، اتصال: USB، زاویه دید: 90 درجه.',
                'brand'        => 'Logitech',
                'price'        => 1200000,
                'quntity'      => 25,
                'category_id'  => 18,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'دوربین وب 4K Ultra HD',
                'description'  => 'کیفیت تصویر: 4K، فریم‌ریت: 60fps، اتصال: USB-C، قابلیت HDR.',
                'brand'        => 'Razer',
                'price'        => 5000000,
                'quntity'      => 15,
                'category_id'  => 18,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'دوربین وب HD اقتصادی',
                'description'  => 'کیفیت تصویر: 720p، فریم‌ریت: 30fps، اتصال: USB، مناسب برای تماس‌های ویدیویی.',
                'brand'        => 'Microsoft',
                'price'        => 800000,
                'quntity'      => 30,
                'category_id'  => 18,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'دوربین وب گیمینگ',
                'description'  => 'کیفیت تصویر: 1080p، فریم‌ریت: 60fps، اتصال: USB، نورپردازی: RGB.',
                'brand'        => 'Razer',
                'price'        => 2500000,
                'quntity'      => 12,
                'category_id'  => 18,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'دوربین وب حرفه‌ای',
                'description'  => 'کیفیت تصویر: 4K، فریم‌ریت: 30fps، اتصال: USB-C، قابلیت تنظیم فوکوس خودکار.',
                'brand'        => 'Logitech',
                'price'        => 4000000,
                'quntity'      => 10,
                'category_id'  => 18,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'دوربین وب هوشمند',
                'description'  => 'کیفیت تصویر: 1080p، فریم‌ریت: 30fps، اتصال: Wi-Fi، قابلیت دنبال کردن حرکت.',
                'brand'        => 'Sony',
                'price'        => 3200000,
                'quntity'      => 14,
                'category_id'  => 18,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'دوربین وب کوچک',
                'description'  => 'کیفیت تصویر: 720p، فریم‌ریت: 30fps، اتصال: USB، طراحی سبک و قابل حمل.',
                'brand'        => 'Anker',
                'price'        => 700000,
                'quntity'      => 35,
                'category_id'  => 18,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'دوربین وب استریو',
                'description'  => 'کیفیت تصویر: 1080p، فریم‌ریت: 60fps، اتصال: USB، میکروفون استریو داخلی.',
                'brand'        => 'Microsoft',
                'price'        => 2000000,
                'quntity'      => 18,
                'category_id'  => 18,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'دوربین وب کنفرانس',
                'description'  => 'کیفیت تصویر: 4K، فریم‌ریت: 30fps، اتصال: USB، زاویه دید: 120 درجه.',
                'brand'        => 'Logitech',
                'price'        => 6000000,
                'quntity'      => 7,
                'category_id'  => 18,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'دوربین وب ساده',
                'description'  => 'کیفیت تصویر: 720p، فریم‌ریت: 30fps، اتصال: USB، طراحی مینیمال.',
                'brand'        => 'Sony',
                'price'        => 900000,
                'quntity'      => 28,
                'category_id'  => 18,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'پرینتر جوهرافشان رنگی',
                'description'  => 'نوع: جوهرافشان، کیفیت چاپ: 4800x1200 dpi، سرعت چاپ: 10 صفحه در دقیقه، اتصال: USB و Wi-Fi.',
                'brand'        => 'HP',
                'price'        => 2500000,
                'quntity'      => 15,
                'category_id'  => 19,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'پرینتر لیزری تک‌رنگ',
                'description'  => 'نوع: لیزری، کیفیت چاپ: 1200x1200 dpi، سرعت چاپ: 20 صفحه در دقیقه، اتصال: USB.',
                'brand'        => 'Canon',
                'price'        => 3000000,
                'quntity'      => 20,
                'category_id'  => 19,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'پرینتر چندکاره جوهرافشان',
                'description'  => 'نوع: جوهرافشان، کیفیت چاپ: 4800x1200 dpi، قابلیت: چاپ، اسکن و کپی، اتصال: Wi-Fi.',
                'brand'        => 'Epson',
                'price'        => 3500000,
                'quntity'      => 12,
                'category_id'  => 19,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'پرینتر لیزری رنگی',
                'description'  => 'نوع: لیزری، کیفیت چاپ: 2400x2400 dpi، سرعت چاپ: 15 صفحه در دقیقه، اتصال: USB-C.',
                'brand'        => 'Brother',
                'price'        => 4500000,
                'quntity'      => 10,
                'category_id'  => 19,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'پرینتر بی‌سیم قابل حمل',
                'description'  => 'نوع: جوهرافشان، کیفیت چاپ: 300x300 dpi، وزن: سبک، اتصال: Bluetooth.',
                'brand'        => 'Canon',
                'price'        => 2000000,
                'quntity'      => 25,
                'category_id'  => 19,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'پرینتر اقتصادی جوهرافشان',
                'description'  => 'نوع: جوهرافشان، کیفیت چاپ: 1200x1200 dpi، سرعت چاپ: 8 صفحه در دقیقه، اتصال: USB.',
                'brand'        => 'HP',
                'price'        => 1500000,
                'quntity'      => 30,
                'category_id'  => 19,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'پرینتر حرارتی',
                'description'  => 'نوع: حرارتی، کیفیت چاپ: 300x300 dpi، مناسب برای چاپ رسید، اتصال: USB.',
                'brand'        => 'Epson',
                'price'        => 1000000,
                'quntity'      => 18,
                'category_id'  => 19,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'پرینتر چندکاره لیزری',
                'description'  => 'نوع: لیزری، کیفیت چاپ: 1200x1200 dpi، قابلیت: چاپ، اسکن، کپی و فکس، اتصال: Wi-Fi.',
                'brand'        => 'Brother',
                'price'        => 5000000,
                'quntity'      => 8,
                'category_id'  => 19,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'پرینتر مخصوص عکس',
                'description'  => 'نوع: جوهرافشان، کیفیت چاپ: 9600x2400 dpi، مناسب برای چاپ عکس، اتصال: USB.',
                'brand'        => 'Canon',
                'price'        => 4000000,
                'quntity'      => 10,
                'category_id'  => 19,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'پرینتر بی‌سیم پیشرفته',
                'description'  => 'نوع: لیزری، کیفیت چاپ: 2400x2400 dpi، سرعت چاپ: 30 صفحه در دقیقه، اتصال: Wi-Fi و Ethernet.',
                'brand'        => 'HP',
                'price'        => 6000000,
                'quntity'      => 6,
                'category_id'  => 19,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'اسکنر تخت A4',
                'description'  => 'نوع: تخت، رزولوشن: 1200x1200 dpi، سرعت اسکن: 10 صفحه در دقیقه، اتصال: USB.',
                'brand'        => 'Canon',
                'price'        => 2000000,
                'quntity'      => 25,
                'category_id'  => 20,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'اسکنر قابل حمل',
                'description'  => 'نوع: دستی، رزولوشن: 600x600 dpi، سرعت اسکن: 5 صفحه در دقیقه، اتصال: USB-C.',
                'brand'        => 'Epson',
                'price'        => 1500000,
                'quntity'      => 30,
                'category_id'  => 20,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'اسکنر حرفه‌ای اسناد',
                'description'  => 'نوع: اسناد، رزولوشن: 2400x2400 dpi، سرعت اسکن: 30 صفحه در دقیقه، اتصال: Ethernet.',
                'brand'        => 'Brother',
                'price'        => 6000000,
                'quntity'      => 12,
                'category_id'  => 20,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'اسکنر عکس A3',
                'description'  => 'نوع: تخت، رزولوشن: 4800x4800 dpi، سرعت اسکن: 8 صفحه در دقیقه، اتصال: Wi-Fi.',
                'brand'        => 'HP',
                'price'        => 5000000,
                'quntity'      => 10,
                'category_id'  => 20,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'اسکنر سریع اسناد',
                'description'  => 'نوع: اسناد، رزولوشن: 1200x1200 dpi، سرعت اسکن: 40 صفحه در دقیقه، اتصال: USB.',
                'brand'        => 'Epson',
                'price'        => 4000000,
                'quntity'      => 15,
                'category_id'  => 20,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'اسکنر اقتصادی A4',
                'description'  => 'نوع: تخت، رزولوشن: 600x600 dpi، سرعت اسکن: 6 صفحه در دقیقه، اتصال: USB.',
                'brand'        => 'Canon',
                'price'        => 1200000,
                'quntity'      => 35,
                'category_id'  => 20,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'اسکنر چندمنظوره',
                'description'  => 'نوع: تخت + اسناد، رزولوشن: 1200x1200 dpi، قابلیت: اسکن اسناد و تصاویر، اتصال: Wi-Fi و USB.',
                'brand'        => 'Brother',
                'price'        => 4500000,
                'quntity'      => 14,
                'category_id'  => 20,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'اسکنر حرفه‌ای عکس',
                'description'  => 'نوع: تخت، رزولوشن: 9600x9600 dpi، سرعت اسکن: 4 صفحه در دقیقه، اتصال: USB-C.',
                'brand'        => 'Epson',
                'price'        => 7500000,
                'quntity'      => 8,
                'category_id'  => 20,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'اسکنر هوشمند',
                'description'  => 'نوع: اسناد، رزولوشن: 1200x1200 dpi، قابلیت: تشخیص متن (OCR)، اتصال: Ethernet و Wi-Fi.',
                'brand'        => 'HP',
                'price'        => 5500000,
                'quntity'      => 9,
                'category_id'  => 20,
                'created_at'   => $this->randomDate(),
            ],
            [
                'name'         => 'اسکنر سریع حرفه‌ای',
                'description'  => 'نوع: اسناد، رزولوشن: 2400x2400 dpi، سرعت اسکن: 50 صفحه در دقیقه، اتصال: USB-C.',
                'brand'        => 'Brother',
                'price'        => 8000000,
                'quntity'      => 6,
                'category_id'  => 20,
                'created_at'   => $this->randomDate(),
            ],


        ]);
    }
    private function randomDate()
    {
        $timestamp = rand(Carbon::now()->subYear()->timestamp, Carbon::now()->timestamp);
        return Carbon::createFromTimestamp($timestamp);
    }
}
